//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappinessIndex.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HappinessIndex.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVITY.
        /// </summary>
        internal static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Custom Enablers.
        /// </summary>
        internal static string AddCustomEnabler {
            get {
                return ResourceManager.GetString("AddCustomEnabler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Successfully..
        /// </summary>
        internal static string AddedSuccessfully {
            get {
                return ResourceManager.GetString("AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT ENABLERS.
        /// </summary>
        internal static string AddOrRemove {
            get {
                return ResourceManager.GetString("AddOrRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALREADY HAVE AN ACCOUNT? .
        /// </summary>
        internal static string AlreadyHaveAnAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anger.
        /// </summary>
        internal static string Anger {
            get {
                return ResourceManager.GetString("Anger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        internal static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anxiety.
        /// </summary>
        internal static string Anxiety {
            get {
                return ResourceManager.GetString("Anxiety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Info.
        /// </summary>
        internal static string AppInfo {
            get {
                return ResourceManager.GetString("AppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoreZen.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Avg Values).
        /// </summary>
        internal static string AvgValues {
            get {
                return ResourceManager.GetString("AvgValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup failed.
        /// </summary>
        internal static string BackupFailed {
            get {
                return ResourceManager.GetString("BackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The manual backup feature currently works only on iOS devices. On Android devices, the default auto backup feature will work to backup the journal data and images..
        /// </summary>
        internal static string BacupFeatureMessage {
            get {
                return ResourceManager.GetString("BacupFeatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUILD - MEASURE - LEARN!.
        /// </summary>
        internal static string BuildMeasureLearn {
            get {
                return ResourceManager.GetString("BuildMeasureLearn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As humans, we are creatures of habit..
        /// </summary>
        internal static string BuildMeasureLearnP1 {
            get {
                return ResourceManager.GetString("BuildMeasureLearnP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our mission is to help people Build Happiness by forming a habit of focusing on what matters most in their lives..
        /// </summary>
        internal static string BuildMeasureLearnP2 {
            get {
                return ResourceManager.GetString("BuildMeasureLearnP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensive research suggests that the main cause of unhappiness is the gap between our expectations and reality..
        /// </summary>
        internal static string BuildMeasureLearnP3 {
            get {
                return ResourceManager.GetString("BuildMeasureLearnP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app will help each person prioritize their personal Happiness Factors. By tracking these factors daily it will help close the gap between expectations and reality to get higher satisfaction on what matters most in life..
        /// </summary>
        internal static string BuildMeasureLearnP4 {
            get {
                return ResourceManager.GetString("BuildMeasureLearnP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will enjoy the glow of happiness as you learn to CoreZen - one day at a time..
        /// </summary>
        internal static string BuildMeasureLearnP5 {
            get {
                return ResourceManager.GetString("BuildMeasureLearnP5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Causes.
        /// </summary>
        internal static string Causes {
            get {
                return ResourceManager.GetString("Causes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenges faced today.
        /// </summary>
        internal static string ChallengesFacedToday {
            get {
                return ResourceManager.GetString("ChallengesFacedToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Your App Language.
        /// </summary>
        internal static string ChooseYourAppLanguage {
            get {
                return ResourceManager.GetString("ChooseYourAppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Cleanliness, Organization).
        /// </summary>
        internal static string CleanlinessOrganization {
            get {
                return ResourceManager.GetString("CleanlinessOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Click on the dots to hide/show the respective graph lines).
        /// </summary>
        internal static string ClickOnTheDotsToHideShowTheRespectiveGraphLines {
            get {
                return ResourceManager.GetString("ClickOnTheDotsToHideShowTheRespectiveGraphLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click save button below to apply all changes.
        /// </summary>
        internal static string ClickSave {
            get {
                return ResourceManager.GetString("ClickSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSE.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close app and stay logged-in.
        /// </summary>
        internal static string CloseAppAndStayLogged_in {
            get {
                return ResourceManager.GetString("CloseAppAndStayLogged-in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon....
        /// </summary>
        internal static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///1. Creation of groups of app users.
        ///2. Sentiment Analysis using Artificial Intelligence.
        ///3. Remedies to overcome emotional discomfort caused by Happiness Inhibitors.
        ///4. Positive Affirmations to cheer up your mood.
        ///5. Connecting Psychologists and Therapists to care seekers..
        /// </summary>
        internal static string ComingSoonContent {
            get {
                return ResourceManager.GetString("ComingSoonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are removing account permanantly. you can not login again. please confirm remove account.
        /// </summary>
        internal static string ConfirmRemoveAccount {
            get {
                return ResourceManager.GetString("ConfirmRemoveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COULD BE BETTER!.
        /// </summary>
        internal static string CouldBeBetter {
            get {
                return ResourceManager.GetString("CouldBeBetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select country.
        /// </summary>
        internal static string CountryValidtionMsg {
            get {
                return ResourceManager.GetString("CountryValidtionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curiosity.
        /// </summary>
        internal static string Curiosity {
            get {
                return ResourceManager.GetString("Curiosity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From here you can add a journal for today or view/edit a journal from a previous day or just browse through the journals saved..
        /// </summary>
        internal static string DashboardContent {
            get {
                return ResourceManager.GetString("DashboardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAY’S SCORE.
        /// </summary>
        internal static string DaysScore {
            get {
                return ResourceManager.GetString("DaysScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISABLE BACKUP.
        /// </summary>
        internal static string DisableBackup {
            get {
                return ResourceManager.GetString("DisableBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DO KNOW YOUR PASSWORD? .
        /// </summary>
        internal static string DoYouKNowYourPassword {
            get {
                return ResourceManager.GetString("DoYouKNowYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT ACTIVITY.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Factors for .
        /// </summary>
        internal static string EditFactorsFor {
            get {
                return ResourceManager.GetString("EditFactorsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT PROFILE.
        /// </summary>
        internal static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the email ID is already registered, please login..
        /// </summary>
        internal static string EmailAlreadyRegistered {
            get {
                return ResourceManager.GetString("EmailAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not supported on this device..
        /// </summary>
        internal static string EmailIsNotSupportedOnThisDevice {
            get {
                return ResourceManager.GetString("EmailIsNotSupportedOnThisDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email has not been registered. Please click on SignUp and register email address..
        /// </summary>
        internal static string EmailNotRegistered {
            get {
                return ResourceManager.GetString("EmailNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Backup.
        /// </summary>
        internal static string EnableBackup {
            get {
                return ResourceManager.GetString("EnableBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Light Background.
        /// </summary>
        internal static string EnableLightTheme {
            get {
                return ResourceManager.GetString("EnableLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enablers.
        /// </summary>
        internal static string Enablers {
            get {
                return ResourceManager.GetString("Enablers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enablers&apos;.
        /// </summary>
        internal static string EnablersReport {
            get {
                return ResourceManager.GetString("EnablersReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email and click forgot password link..
        /// </summary>
        internal static string EnterYourEmailToReset {
            get {
                return ResourceManager.GetString("EnterYourEmailToReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER YOUR NAME AND EMAIL TO CONTINUE.
        /// </summary>
        internal static string EnterYourNameAndEmail {
            get {
                return ResourceManager.GetString("EnterYourNameAndEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Profile Password.
        /// </summary>
        internal static string EnterYourProfilePassword {
            get {
                return ResourceManager.GetString("EnterYourProfilePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envy.
        /// </summary>
        internal static string Envy {
            get {
                return ResourceManager.GetString("Envy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXCELLENT!.
        /// </summary>
        internal static string Excellent {
            get {
                return ResourceManager.GetString("Excellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise.
        /// </summary>
        internal static string Exercise {
            get {
                return ResourceManager.GetString("Exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expectation.
        /// </summary>
        internal static string Expectation {
            get {
                return ResourceManager.GetString("Expectation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXTREME.
        /// </summary>
        internal static string Extreme {
            get {
                return ResourceManager.GetString("Extreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All saved edits will apply to today’s Journal. Please visit the Today’s Score page to mark the satisfaction scores on any newly added Enablers..
        /// </summary>
        internal static string FactorChangeWarning {
            get {
                return ResourceManager.GetString("FactorChangeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY SCORE.
        /// </summary>
        internal static string Factors {
            get {
                return ResourceManager.GetString("Factors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happiness Enablers.
        /// </summary>
        internal static string FactorsList {
            get {
                return ResourceManager.GetString("FactorsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can select your happiness determining factors from the given  list or click the ADD button on top to create your own happiness enablers and use it. You can create wishlists under each happiness enabler and share them with others..
        /// </summary>
        internal static string FactorsListContent {
            get {
                return ResourceManager.GetString("FactorsListContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAIR!.
        /// </summary>
        internal static string Fair {
            get {
                return ResourceManager.GetString("Fair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        internal static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAVOURITE.
        /// </summary>
        internal static string Favourites {
            get {
                return ResourceManager.GetString("Favourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fear.
        /// </summary>
        internal static string Fear {
            get {
                return ResourceManager.GetString("Fear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEEDBACK.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As we strive to improve the app and the user experience, we would appreciate getting your feedback via email, sent to: .
        /// </summary>
        internal static string FeedbackContent {
            get {
                return ResourceManager.GetString("FeedbackContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback on CoreZen app.
        /// </summary>
        internal static string FeedbackOnBuildHappinessApp {
            get {
                return ResourceManager.GetString("FeedbackOnBuildHappinessApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        internal static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORGOT PASSWORD.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Forgot password? Logout from the side menu to find forgot password link).
        /// </summary>
        internal static string ForgotPasswordMenuGuide {
            get {
                return ResourceManager.GetString("ForgotPasswordMenuGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From : .
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET STARTED.
        /// </summary>
        internal static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOOD!.
        /// </summary>
        internal static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Afternoon, .
        /// </summary>
        internal static string GoodAfternoon {
            get {
                return ResourceManager.GetString("GoodAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Evening, .
        /// </summary>
        internal static string GoodEvening {
            get {
                return ResourceManager.GetString("GoodEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Morning, .
        /// </summary>
        internal static string GoodMorning {
            get {
                return ResourceManager.GetString("GoodMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GO TO JOURNALS.
        /// </summary>
        internal static string GoToJournals {
            get {
                return ResourceManager.GetString("GoToJournals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gratitude Journal &amp; Reports .
        /// </summary>
        internal static string GratitudeJournalReports {
            get {
                return ResourceManager.GetString("GratitudeJournalReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greed.
        /// </summary>
        internal static string Greed {
            get {
                return ResourceManager.GetString("Greed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guilt.
        /// </summary>
        internal static string Guilt {
            get {
                return ResourceManager.GetString("Guilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happiness.
        /// </summary>
        internal static string happiness {
            get {
                return ResourceManager.GetString("happiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAPPINESS ENABLERS SETUP.
        /// </summary>
        internal static string happinessEnablersSetup {
            get {
                return ResourceManager.GetString("happinessEnablersSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happiness Enablers.
        /// </summary>
        internal static string HappinessFactors {
            get {
                return ResourceManager.GetString("HappinessFactors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happiness Journal Entry.
        /// </summary>
        internal static string HappinessJournalEntry {
            get {
                return ResourceManager.GetString("HappinessJournalEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your everyday journal entry page where you mark your satisfaction score for your day and the chosen happiness enablers..
        /// </summary>
        internal static string HappinessJournalEntryContent {
            get {
                return ResourceManager.GetString("HappinessJournalEntryContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOURNAL FOR .
        /// </summary>
        internal static string HappinessJournalFor {
            get {
                return ResourceManager.GetString("HappinessJournalFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inhibitors.
        /// </summary>
        internal static string HappinessJournalHighlights {
            get {
                return ResourceManager.GetString("HappinessJournalHighlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A section to check on your happiness inhibitors and mark how they are affecting your happiness..
        /// </summary>
        internal static string HappinessJournalHighlightsContent {
            get {
                return ResourceManager.GetString("HappinessJournalHighlightsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satisfaction Score.
        /// </summary>
        internal static string HappinessScore {
            get {
                return ResourceManager.GetString("HappinessScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happiness Score by Factor.
        /// </summary>
        internal static string HappinessScorebyFactor {
            get {
                return ResourceManager.GetString("HappinessScorebyFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi .
        /// </summary>
        internal static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIGH.
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOURNAL NOTES.
        /// </summary>
        internal static string HighlightsOfTheDay {
            get {
                return ResourceManager.GetString("HighlightsOfTheDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeAppTour {
            get {
                return ResourceManager.GetString("HomeAppTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        internal static string HomeMenu {
            get {
                return ResourceManager.GetString("HomeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Pets.
        /// </summary>
        internal static string House_Pets {
            get {
                return ResourceManager.GetString("House Pets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record your satisfaction score.
        /// </summary>
        internal static string HowWasYourDay {
            get {
                return ResourceManager.GetString("HowWasYourDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to enable the data backup from the App to your iCloud?.
        /// </summary>
        internal static string iCloucBackupPermission {
            get {
                return ResourceManager.GetString("iCloucBackupPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inhibitors.
        /// </summary>
        internal static string Inhibitors {
            get {
                return ResourceManager.GetString("Inhibitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inhibitors&apos;.
        /// </summary>
        internal static string InhibitorsReport {
            get {
                return ResourceManager.GetString("InhibitorsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A visual representation of the level of effect of each Inhibitor along with the changes in effect during the day as recorded. The report also shows the notes entered on sentiments, causes, and what helped improve the feeling. All reports along with details can be shared via email with others..
        /// </summary>
        internal static string InhibitorsReportAppTourContent {
            get {
                return ResourceManager.GetString("InhibitorsReportAppTourContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happiness Inhibitors&apos; Report.
        /// </summary>
        internal static string InhibitorsReportAppTourTitle {
            get {
                return ResourceManager.GetString("InhibitorsReportAppTourTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAPPINESS INHIBITORS.
        /// </summary>
        internal static string InhibitorsUpperCase {
            get {
                return ResourceManager.GetString("InhibitorsUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the legend to Show/Hide the visibility of the inhibitor.
        /// </summary>
        internal static string InhibitorTooltipForNewUser {
            get {
                return ResourceManager.GetString("InhibitorTooltipForNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid answer to reset the password..
        /// </summary>
        internal static string InvalidAnswer {
            get {
                return ResourceManager.GetString("InvalidAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password..
        /// </summary>
        internal static string InvalidInputPassword {
            get {
                return ResourceManager.GetString("InvalidInputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid confirm password..
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name or password..
        /// </summary>
        internal static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In what city or town was your first job?.
        /// </summary>
        internal static string InWhatCityOrTownWasYourFirstJob {
            get {
                return ResourceManager.GetString("InWhatCityOrTownWasYourFirstJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is missing.
        /// </summary>
        internal static string IsMissing {
            get {
                return ResourceManager.GetString("IsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remainder for .
        /// </summary>
        internal static string ItsTimeforYourWorkout {
            get {
                return ResourceManager.GetString("ItsTimeforYourWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jealousy.
        /// </summary>
        internal static string Jealousy {
            get {
                return ResourceManager.GetString("Jealousy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOURNAL.
        /// </summary>
        internal static string Journal {
            get {
                return ResourceManager.GetString("Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day’s Score.
        /// </summary>
        internal static string JournalAppTourTitle {
            get {
                return ResourceManager.GetString("JournalAppTourTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Day’s Score&quot; entered for {0} on {1} will be deleted.
        /// </summary>
        internal static string JournalDeleteWarning {
            get {
                return ResourceManager.GetString("JournalDeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOURNALS.
        /// </summary>
        internal static string Journals {
            get {
                return ResourceManager.GetString("Journals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANGUAGES.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lessons learned today.
        /// </summary>
        internal static string LessonsLearntToday {
            get {
                return ResourceManager.GetString("LessonsLearntToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s get started with your micro workouts!.
        /// </summary>
        internal static string LetsGetStarted {
            get {
                return ResourceManager.GetString("LetsGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGOUT.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loneliness.
        /// </summary>
        internal static string Loneliness {
            get {
                return ResourceManager.GetString("Loneliness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Love.
        /// </summary>
        internal static string Love {
            get {
                return ResourceManager.GetString("Love", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOW.
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Meditation, Peace, Spirituality).
        /// </summary>
        internal static string MeditationPeaceSpirituality {
            get {
                return ResourceManager.GetString("MeditationPeaceSpirituality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEDIUM.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Micro Workouts.
        /// </summary>
        internal static string MicroWorkout {
            get {
                return ResourceManager.GetString("MicroWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micro Workout Description.
        /// </summary>
        internal static string MicroWorkoutDescription {
            get {
                return ResourceManager.GetString("MicroWorkoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micro Workout Duration.
        /// </summary>
        internal static string MicroWorkoutDuration {
            get {
                return ResourceManager.GetString("MicroWorkoutDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micro Workout Name.
        /// </summary>
        internal static string MicroWorkoutName {
            get {
                return ResourceManager.GetString("MicroWorkoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORKOUTS.
        /// </summary>
        internal static string MicroWorkoutOnly {
            get {
                return ResourceManager.GetString("MicroWorkoutOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MICRO-WORKOUTS.
        /// </summary>
        internal static string MicroWorkoutsSetup {
            get {
                return ResourceManager.GetString("MicroWorkoutsSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mind.
        /// </summary>
        internal static string Mind {
            get {
                return ResourceManager.GetString("Mind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIND - MICRO-WORKOUTS.
        /// </summary>
        internal static string MindWorkoutsSetup {
            get {
                return ResourceManager.GetString("MindWorkoutsSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money.
        /// </summary>
        internal static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music/Movies.
        /// </summary>
        internal static string Music_Movies {
            get {
                return ResourceManager.GetString("Music/Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY JOURNAL.
        /// </summary>
        internal static string MyJournal {
            get {
                return ResourceManager.GetString("MyJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAPPINESS INHIBITORS.
        /// </summary>
        internal static string NegativeThoughtsToday {
            get {
                return ResourceManager.GetString("NegativeThoughtsToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negativity.
        /// </summary>
        internal static string Negativity {
            get {
                return ResourceManager.GetString("Negativity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, Log me Out.
        /// </summary>
        internal static string NoLogMeOut {
            get {
                return ResourceManager.GetString("NoLogMeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NONE.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found at the dates selected..
        /// </summary>
        internal static string NoRecordsFound {
            get {
                return ResourceManager.GetString("NoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Remove Account.
        /// </summary>
        internal static string NoRemoveAccount {
            get {
                return ResourceManager.GetString("NoRemoveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feelings.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A place to write your everyday gratitude journal along with the challenges faced during the day and any lessons learned..
        /// </summary>
        internal static string NotesAppTourContent {
            get {
                return ResourceManager.GetString("NotesAppTourContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        internal static string NotesAppTourTitle {
            get {
                return ResourceManager.GetString("NotesAppTourTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes for .
        /// </summary>
        internal static string NotesFor {
            get {
                return ResourceManager.GetString("NotesFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to any notes for your journal?.
        /// </summary>
        internal static string NotificationMessage {
            get {
                return ResourceManager.GetString("NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users found on this device, please provide your name and email to continue..
        /// </summary>
        internal static string NoUserFound {
            get {
                return ResourceManager.GetString("NoUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sets :.
        /// </summary>
        internal static string NumberofSets {
            get {
                return ResourceManager.GetString("NumberofSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Organization, Cleanliness).
        /// </summary>
        internal static string OrganizationCleanliness {
            get {
                return ResourceManager.GetString("OrganizationCleanliness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Day&apos;s Score.
        /// </summary>
        internal static string OverallDaysScore {
            get {
                return ResourceManager.GetString("OverallDaysScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satisfaction score for reporting period.
        /// </summary>
        internal static string OverallHappinessScore {
            get {
                return ResourceManager.GetString("OverallHappinessScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been successfully reset..
        /// </summary>
        internal static string PasswordResetSuccessfully {
            get {
                return ResourceManager.GetString("PasswordResetSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string Personal_Information {
            get {
                return ResourceManager.GetString("Personal Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERSONAL NOTES.
        /// </summary>
        internal static string PersonalNote {
            get {
                return ResourceManager.GetString("PersonalNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Note.
        /// </summary>
        internal static string PersonalNoteAppTour {
            get {
                return ResourceManager.GetString("PersonalNoteAppTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A hidden away section to launch a screen for entering some personal notes that are password protected..
        /// </summary>
        internal static string PersonalNoteAppTourContent {
            get {
                return ResourceManager.GetString("PersonalNoteAppTourContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal note : .
        /// </summary>
        internal static string PersonalNoteLower {
            get {
                return ResourceManager.GetString("PersonalNoteLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a photo from album.
        /// </summary>
        internal static string PickAPhotoFromAlbum {
            get {
                return ResourceManager.GetString("PickAPhotoFromAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name.
        /// </summary>
        internal static string PleaseEnterYourName {
            get {
                return ResourceManager.GetString("PleaseEnterYourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum of 7 factors are allowed. Please deselect one or more to select any others..
        /// </summary>
        internal static string PleaseSelectAMaximumOf6Factors {
            get {
                return ResourceManager.GetString("PleaseSelectAMaximumOf6Factors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a minimum of 2 factors..
        /// </summary>
        internal static string PleaseSelectAMinimumOf2Factors {
            get {
                return ResourceManager.GetString("PleaseSelectAMinimumOf2Factors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an image for today&apos;s journal..
        /// </summary>
        internal static string PleaseSelectAnImageForTodaysJournal {
            get {
                return ResourceManager.GetString("PleaseSelectAnImageForTodaysJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign-in using your iCloud account on your device through ‘Settings’, to  enable the use of the backup of your happiness journal..
        /// </summary>
        internal static string PleaseSigningUsingYouriCloudAccount {
            get {
                return ResourceManager.GetString("PleaseSigningUsingYouriCloudAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFILE.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APP TOUR.
        /// </summary>
        internal static string QuickTour {
            get {
                return ResourceManager.GetString("QuickTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;M READY.
        /// </summary>
        internal static string ReadyButton {
            get {
                return ResourceManager.GetString("ReadyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you ready to start recording your Happiness Journal for .
        /// </summary>
        internal static string ReadyMessage {
            get {
                return ResourceManager.GetString("ReadyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reality.
        /// </summary>
        internal static string Reality {
            get {
                return ResourceManager.GetString("Reality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminders.
        /// </summary>
        internal static string Reminders {
            get {
                return ResourceManager.GetString("Reminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMOVE ACCOUNT.
        /// </summary>
        internal static string RemoveAccount {
            get {
                return ResourceManager.GetString("RemoveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Generated for .
        /// </summary>
        internal static string ReportFor {
            get {
                return ResourceManager.GetString("ReportFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Generated for period - .
        /// </summary>
        internal static string ReportGeneratedFrom {
            get {
                return ResourceManager.GetString("ReportGeneratedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORTS.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happiness Enablers&apos; Report.
        /// </summary>
        internal static string ReportsAppTourTitle {
            get {
                return ResourceManager.GetString("ReportsAppTourTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A graphical representation of your  daily happiness score. Weekly and monthly averages are also available using the date range selection..
        /// </summary>
        internal static string ReportsContent {
            get {
                return ResourceManager.GetString("ReportsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Reportssmall {
            get {
                return ResourceManager.GetString("Reportssmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESET.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESET PASSWORD.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest Duration(Min/Sec) : .
        /// </summary>
        internal static string RestDuration {
            get {
                return ResourceManager.GetString("RestDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadness.
        /// </summary>
        internal static string Sadness {
            get {
                return ResourceManager.GetString("Sadness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SATISFACTION SCORE.
        /// </summary>
        internal static string SatisfactionScore {
            get {
                return ResourceManager.GetString("SatisfactionScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Successfully..
        /// </summary>
        internal static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please save this screen to be able to share the wishlist.
        /// </summary>
        internal static string SaveMessage {
            get {
                return ResourceManager.GetString("SaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Search for knowledge, Intellectual).
        /// </summary>
        internal static string SearchForKnowledgeIntellectual {
            get {
                return ResourceManager.GetString("SearchForKnowledgeIntellectual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Past Activity: .
        /// </summary>
        internal static string SearchForPastJournal {
            get {
                return ResourceManager.GetString("SearchForPastJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Answer.
        /// </summary>
        internal static string SecurityAnswer {
            get {
                return ResourceManager.GetString("SecurityAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Question.
        /// </summary>
        internal static string SecurityQuestion {
            get {
                return ResourceManager.GetString("SecurityQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Make your selection from the list below).
        /// </summary>
        internal static string SelectDefaultMicroWorkouts {
            get {
                return ResourceManager.GetString("SelectDefaultMicroWorkouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Date : .
        /// </summary>
        internal static string SelectTheDate {
            get {
                return ResourceManager.GetString("SelectTheDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAPPINESS ENABLERS.
        /// </summary>
        internal static string SelectYourFactors {
            get {
                return ResourceManager.GetString("SelectYourFactors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET PASSWORD.
        /// </summary>
        internal static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsAppTour {
            get {
                return ResourceManager.GetString("SettingsAppTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A variety of personalization settings for background color, enabling/disabling backup of data to your iCloud or google drive, and personal profile information entry etc..
        /// </summary>
        internal static string SettingsAppTourContent {
            get {
                return ResourceManager.GetString("SettingsAppTourContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your password for your login profile to have safe access to your personal note..
        /// </summary>
        internal static string SetYourPassword {
            get {
                return ResourceManager.GetString("SetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGNUP.
        /// </summary>
        internal static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Contact.
        /// </summary>
        internal static string Social_Contact {
            get {
                return ResourceManager.GetString("Social Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START WORKOUT.
        /// </summary>
        internal static string StartWorkout {
            get {
                return ResourceManager.GetString("StartWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select state.
        /// </summary>
        internal static string StateValidtionMsg {
            get {
                return ResourceManager.GetString("StateValidtionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully registered..
        /// </summary>
        internal static string SuccessfullyRegistered {
            get {
                return ResourceManager.GetString("SuccessfullyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a picture.
        /// </summary>
        internal static string TakeAPicture {
            get {
                return ResourceManager.GetString("TakeAPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERRIBLE!.
        /// </summary>
        internal static string Terrible {
            get {
                return ResourceManager.GetString("Terrible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are you grateful for, today?.
        /// </summary>
        internal static string TheBestThingThatHappenedToday {
            get {
                return ResourceManager.GetString("TheBestThingThatHappenedToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Their effect on your happiness).
        /// </summary>
        internal static string TheirEffectOnYourHappiness {
            get {
                return ResourceManager.GetString("TheirEffectOnYourHappiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Day’s Score&quot; for .
        /// </summary>
        internal static string TheJournalEntryFor {
            get {
                return ResourceManager.GetString("TheJournalEntryFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time in seconds.
        /// </summary>
        internal static string Timeinseconds {
            get {
                return ResourceManager.GetString("Timeinseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To : .
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to .
        /// </summary>
        internal static string To1 {
            get {
                return ResourceManager.GetString("To1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Today).
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tranquility.
        /// </summary>
        internal static string Tranquility {
            get {
                return ResourceManager.GetString("Tranquility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travelling.
        /// </summary>
        internal static string Travelling {
            get {
                return ResourceManager.GetString("Travelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded Successfully..
        /// </summary>
        internal static string UploadedSuccessfully {
            get {
                return ResourceManager.GetString("UploadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTACH IMAGE.
        /// </summary>
        internal static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD ACTIVITY.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW APP TOUR.
        /// </summary>
        internal static string ViewAppTour {
            get {
                return ResourceManager.GetString("ViewAppTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What helped.
        /// </summary>
        internal static string WhatHelped {
            get {
                return ResourceManager.GetString("WhatHelped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the name of the first school you attended?.
        /// </summary>
        internal static string WhatIsTheNameOfTheFirstSchoolYouAttended {
            get {
                return ResourceManager.GetString("WhatIsTheNameOfTheFirstSchoolYouAttended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the name of your favorite childhood friend?.
        /// </summary>
        internal static string WhatIsTheNameOfYourFaVoriteChildhoodFriend {
            get {
                return ResourceManager.GetString("WhatIsTheNameOfYourFaVoriteChildhoodFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your grandmother&apos;s first name?.
        /// </summary>
        internal static string WhatIsYourGrandmothersFirstName {
            get {
                return ResourceManager.GetString("WhatIsYourGrandmothersFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was your childhood nickname?.
        /// </summary>
        internal static string WhatWasYourChildhoodNickname {
            get {
                return ResourceManager.GetString("WhatWasYourChildhoodNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was your dream job as a child?.
        /// </summary>
        internal static string WhatWasYourDreamJobAsAChild {
            get {
                return ResourceManager.GetString("WhatWasYourDreamJobAsAChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was your first car?.
        /// </summary>
        internal static string WhatWasYourFirstCar {
            get {
                return ResourceManager.GetString("WhatWasYourFirstCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wishlist 1.
        /// </summary>
        internal static string Wishlist1 {
            get {
                return ResourceManager.GetString("Wishlist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wishlist 2.
        /// </summary>
        internal static string Wishlist2 {
            get {
                return ResourceManager.GetString("Wishlist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wishlist 3.
        /// </summary>
        internal static string Wishlist3 {
            get {
                return ResourceManager.GetString("Wishlist3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        internal static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout Duration(Min/Sec) :.
        /// </summary>
        internal static string WorkoutDuration {
            get {
                return ResourceManager.GetString("WorkoutDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout In Progress.
        /// </summary>
        internal static string WorkoutInProgress {
            get {
                return ResourceManager.GetString("WorkoutInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micro Workouts&apos;.
        /// </summary>
        internal static string WorkoutReport {
            get {
                return ResourceManager.GetString("WorkoutReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Day.
        /// </summary>
        internal static string YourDay {
            get {
                return ResourceManager.GetString("YourDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR HAPPINESS SCORE.
        /// </summary>
        internal static string YourHappinessScore {
            get {
                return ResourceManager.GetString("YourHappinessScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR INHIBITOR EFFECT SCORE.
        /// </summary>
        internal static string YourInhibitorEffectScore {
            get {
                return ResourceManager.GetString("YourInhibitorEffectScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Your Personal Happiness Determining Factors).
        /// </summary>
        internal static string YourPersonalHappinessDeterminingFactors {
            get {
                return ResourceManager.GetString("YourPersonalHappinessDeterminingFactors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube Link.
        /// </summary>
        internal static string YoutubeLink {
            get {
                return ResourceManager.GetString("YoutubeLink", resourceCulture);
            }
        }
    }
}
